### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by jtv7** [rsgalloway/dropcam#13]
When I try to login I get this error.  I am certain my credentials are correct, a possible bug?:

login failed and returned status code 200. login json: {"status": 400, "items": [], "status_description": "bad-request", "status_detail": "The username and password do not match"}
Traceback (most recent call last):
  File "dropcam.py", line 267, in <module>
    os.getenv("password"))
  File "dropcam.py", line 127, in __init__
    self._login()
  File "dropcam.py", line 139, in _login
    raise Exception
Exception

**Comment by rsgalloway** [comment]
Thanks for the report. Unfortunately, I was not able to reproduce this when using my correct username/pw. I was able to reproduce it by giving a bad pw, however. 

How are you setting these values in your environment? 

Try verifying the values using 
```python
print os.getenv("DROPCAM_USERNAME"), os.getenv("DROPCAM_PASSWORD")
```

Or just create the Dropcam object like this:

```python
import dropcam
d = dropcam.Dropcam("myusername", "mypass")
```

**Comment by jtv7** [comment]
You are correct, I did not set the values correctly.  Thank you for your quick reply.
