### ISSUE TITLE
405 error when login

### ISSUE THREAD

**Issue by hunterchung** [rsgalloway/dropcam#14]
I tried to create a dropcam obj using `d = Dropcam(<MY USERNAME>, <MY PASSWORD>)` and get error `HTTPError: HTTP Error 405: METHOD NOT ALLOWED`. Should I use the username and password to login Dropcam website or something else?

**Comment by rsgalloway** [comment]
You should use the same credentials as the website. That said, please make sure you're using the latest version: 0.3.2.

**Comment by hunterchung** [comment]
Thanks for your response. Actually I can find either version `0.3.1` or `0.4.0`, but not `0.3.2`. I got the error `HTTPError: HTTP Error 405: METHOD NOT ALLOWED` using `0.3.1` and `Exception: Gateway Timeout` using `0.4.0`. Could you help me with this?

**Comment by rsgalloway** [comment]
Ah, sorry, 0.3.2 is not a tag, it's the head of the repo. Can you try with that and report back?

**Comment by hunterchung** [comment]
It works! Thanks for your help.
