### ISSUE TITLE
why does pypi think version 0.4.0 is a thing?

### ISSUE THREAD

**Issue by tedder** [rsgalloway/dropcam#16]
This repo shows 0.3.2. But [pypi says 0.4.0](https://pypi.python.org/pypi/dropcam/). Did you release a 0.4.0 and then pull it back?

**Comment by tedder** [comment]
I'm just lazy. I'd rather not have to manually deploy 0.3.2 :)

**Comment by rsgalloway** [comment]
Ha, no worries, it needs to be fixed.

**Comment by rsgalloway** [comment]
fixed

https://pypi.python.org/pypi/dropcam/0.3.2
