### ISSUE TITLE
login failure

### ISSUE THREAD

**Issue by zachheine** [rsgalloway/dropcam#17]
login failed and returned status code 200. login json: {"status": 400, "items": [], "status_description": "bad-request", "status_detail": "No user is identified with this information."}

These same credentials work with this other library: https://github.com/alexlincoln/dropcam.

**Comment by rsgalloway** [comment]
Hmm, not sure why it works with the other API, but I was able to log in as usual, but I had to use my email address instead of the username. Did you convert your account from dropcam to nest yet?

**Comment by ylmeng** [comment]
I cannot log in either, and get a 403 error (unauthorized).

**Comment by rsgalloway** [comment]
Hey guys, sorry for the late response... is this still an issue? I haven't updated my (really) old dropcam's firmware since they were acquired by nest, but I can still login using my account, I just can't get any camera data.

```
>>> from dropcam import Dropcam
>>> Dropcam("XXXX", "XXXX")
<dropcam.Dropcam object at 0xae2c90>
```

**Comment by rsgalloway** [comment]
@ylmeng I just re-read your comment: make sure you're using the same email address you use to log in to your nest.com account: 

`>>> Dropcam("my-email-address@foobar.com", <password>)`
